%%Script to adjust different spectra with lorentzian functions
load('V=0.4.mat');

Photocurrent(:)=MeasurementData.LI(1,1,:);
SMcurrent(:)=MeasurementData.SM.I(1,1,:);
WL(:)=MeasurementData.WL(1,1,:);
E=1240./(WL-25);
%normalization and smooth to the exciton A peak
%Pnorm=smoothdata(Photocurrent/max(Photocurrent),'sgolay',5);
Pnorm=Photocurrent/max(Photocurrent);
%plotdata
figure;plot(E,Pnorm,'.');
%lorentzianfit
Numberofpeaks=4;%select the number of peaks
LF=@(I,x0,gamma,x) I./(1+((x-x0)/gamma).^2);%lorentzianfunction
options = optimoptions('lsqcurvefit','MaxFunEvals',10000,'MaxIter',2000);

if Numberofpeaks==1
    Fit=@(p,x) LF(p(1),p(2),p(3),x)+p(4);
    guess=[1 1.9 0.1 1];
    lb=[0 1.8 0 0];
    ub=[inf inf inf inf];
    p(:,1)=lsqcurvefit(Fit,guess,E,Pnorm,lb,ub,options);
    figure; hold on; plot(E,Pnorm,'r.');
    plot(E,Fit(p,E),'b');
    plot(E,LF(p(1),p(2),p(3),E),'k');
    hold off
elseif Numberofpeaks==2
    Fit=@(p,x) LF(p(1),p(2),p(3),x)+...
        LF(p(4),p(5),p(6),x)+...
        p(7);
    guess=[1 1.9 0.1 ...
           1 2 0.1 ...
           1];
    lb=[0 1.8 0 ...
        0 1.8 0 ...
        0];
    ub=[inf 3 inf ... 
        inf 3 inf ... 
        inf];
    p(:,1)=lsqcurvefit(Fit,guess,E,Pnorm,lb,ub,options);
    figure; hold on; plot(E,Pnorm,'r.');plot(E,Fit(p,E),'b');
    plot(E,LF(p(1),p(2),p(3),E),'k'),plot(E,LF(p(4),p(5),p(6),E),'k');
    hold off
elseif Numberofpeaks==3
    Fit=@(p,x) LF(p(1),p(2),p(3),x)+...
        LF(p(4),p(5),p(6),x)+...
        LF(p(7),p(8),p(9),x)+p(10);
    guess=[1 1.9 0.1...
        1 1.9 0.1...
        1 2 0.1...
        1];
    lb=[0 1.8 0 ...
        0 1.8 0 ...
        0 1.9 0 ...
        0];
    ub=[inf 3 inf...
        inf 3 inf...
        inf 3 inf...
        inf];
    p(:,1)=lsqcurvefit(Fit,guess,E,Pnorm,lb,ub,options);
    figure; hold on; plot(E,Pnorm,'r.');plot(E,Fit(p,E),'b');
    plot(E,LF(p(1),p(2),p(3),E),'k');plot(E,LF(p(4),p(5),p(6),E),'k');
    plot(E,LF(p(7),p(8),p(9),E),'k');
    hold off
elseif Numberofpeaks==4
    Fit=@(p,x) LF(p(1),p(2),p(3),x)+...
        LF(p(4),p(5),p(6),x)+...
        LF(p(7),p(8),p(9),x)+...
        LF(p(10),p(11),p(12),x)+p(13);
    guess=[1 1.9 0.1...
        1 1.9 0.1 ...
        1 2 0.1...
        1 2 0.1 ...
        1];
    lb=[0 1.8 0 ...
        0 1.8 0 ...
        0 1.8 0 ...
        0 1.8 0 ... 
        0];
    ub=[inf 2.2 inf ...
        inf 2.2 inf ...
        inf 2.2 inf ...
        inf 2.2 inf ...
        inf];
    p(:,1)=lsqcurvefit(Fit,guess,E,Pnorm,lb,ub,options);
    figure; hold on; plot(E,Pnorm,'r.');plot(E,Fit(p,E),'b');
    plot(E,LF(p(1),p(2),p(3),E),'k');plot(E,LF(p(4),p(5),p(6),E),'k');
    plot(E,LF(p(7),p(8),p(9),E),'k');plot(E,LF(p(10),p(11),p(12),E),'k');
    hold off
elseif Numberofpeaks==5
    Fit=@(p,x) LF(p(1),p(2),p(3),x)+...
        LF(p(4),p(5),p(6),x)+...
        LF(p(7),p(8),p(9),x)+...
        LF(p(10),p(11),p(12),x)+...
        LF(p(13),p(14),p(15),x)+...
        p(16);
    guess=[1 1.9 0.1 ...
           1 1.9 0.1 ...
           1 1.9 0.1 ...
           1 1.9 0.1 ...
           1 1.9 0.1 ...
            1];
    lb=[0 1.8 0 ...
        0 1.8 0 ... 
        0 1.8 0 ...
        0 1.8 0 ...
        0 1.8 0 ...
        0];
    ub=[inf 2.5 inf ...
        inf 2.5 inf ...
        inf 2.5 inf ...
        inf 2.5 inf ...
        inf 2.5 inf ...
        inf];
    p(:,1)=lsqcurvefit(Fit,guess,E,Pnorm,lb,ub,options);
    figure; hold on; plot(E,Pnorm,'r.');plot(E,Fit(p,E),'b');
    plot(E,LF(p(1),p(2),p(3),E),'k');plot(E,LF(p(4),p(5),p(6),E),'k');
    plot(E,LF(p(7),p(8),p(9),E),'k');plot(E,LF(p(10),p(11),p(12),E),'k');
    plot(E,LF(p(13),p(14),p(15),E),'k');
    
end
clear p